// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bids.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countBidsByProduct = `-- name: CountBidsByProduct :one
SELECT COUNT(*) FROM bids
WHERE product_id = $1 AND is_valid = true
`

func (q *Queries) CountBidsByProduct(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBidsByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBid = `-- name: CreateBid :exec
INSERT INTO bids (
    product_id,
    user_id,
    price,
    comments
) VALUES (
    $1, $2, $3, $4
)
`

type CreateBidParams struct {
	ProductID uuid.UUID `json:"product_id"`
	UserID    uuid.UUID `json:"user_id"`
	Price     int32     `json:"price"`
	Comments  *string   `json:"comments"`
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) error {
	_, err := q.db.Exec(ctx, createBid,
		arg.ProductID,
		arg.UserID,
		arg.Price,
		arg.Comments,
	)
	return err
}

const deleteBid = `-- name: DeleteBid :exec
DELETE FROM bids
WHERE id = $1
`

func (q *Queries) DeleteBid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBid, id)
	return err
}

const getBidsByProductID = `-- name: GetBidsByProductID :many
SELECT id, bid_at, product_id, user_id, price, is_valid, comments FROM bids
WHERE product_id = $1
ORDER BY bid_at DESC
`

func (q *Queries) GetBidsByProductID(ctx context.Context, productID uuid.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getBidsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bid{}
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.BidAt,
			&i.ProductID,
			&i.UserID,
			&i.Price,
			&i.IsValid,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBidsByUserID = `-- name: GetBidsByUserID :many
SELECT id, bid_at, product_id, user_id, price, is_valid, comments FROM bids
WHERE user_id = $1
ORDER BY bid_at DESC
`

func (q *Queries) GetBidsByUserID(ctx context.Context, userID uuid.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getBidsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bid{}
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.BidAt,
			&i.ProductID,
			&i.UserID,
			&i.Price,
			&i.IsValid,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBidForProduct = `-- name: GetLatestBidForProduct :one
SELECT id, bid_at, product_id, user_id, price, is_valid, comments FROM bids
WHERE product_id = $1 AND is_valid = true
ORDER BY bid_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBidForProduct(ctx context.Context, productID uuid.UUID) (Bid, error) {
	row := q.db.QueryRow(ctx, getLatestBidForProduct, productID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.BidAt,
		&i.ProductID,
		&i.UserID,
		&i.Price,
		&i.IsValid,
		&i.Comments,
	)
	return i, err
}

const getValidBidsByProductID = `-- name: GetValidBidsByProductID :many
SELECT id, bid_at, product_id, user_id, price, is_valid, comments FROM bids
WHERE product_id = $1 AND is_valid = true
ORDER BY bid_at DESC
`

func (q *Queries) GetValidBidsByProductID(ctx context.Context, productID uuid.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getValidBidsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bid{}
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.BidAt,
			&i.ProductID,
			&i.UserID,
			&i.Price,
			&i.IsValid,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invalidateBid = `-- name: InvalidateBid :exec
UPDATE bids
SET is_valid = false
WHERE id = $1
`

func (q *Queries) InvalidateBid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateBid, id)
	return err
}
