// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addProduct = `-- name: AddProduct :one
INSERT INTO products (
    title,
    description,
    seller_id,
    images,
    min_price,
    current_price
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, title, description, seller_id, images, min_price, current_price, created_at, updated_at, sold_at, sold_to
`

type AddProductParams struct {
	Title        string    `json:"title"`
	Description  *string   `json:"description"`
	SellerID     uuid.UUID `json:"seller_id"`
	Images       []string  `json:"images"`
	MinPrice     int32     `json:"min_price"`
	CurrentPrice int32     `json:"current_price"`
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, addProduct,
		arg.Title,
		arg.Description,
		arg.SellerID,
		arg.Images,
		arg.MinPrice,
		arg.CurrentPrice,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SellerID,
		&i.Images,
		&i.MinPrice,
		&i.CurrentPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SoldAt,
		&i.SoldTo,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, title, description, seller_id, images, min_price, current_price, created_at, updated_at, sold_at, sold_to FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SellerID,
		&i.Images,
		&i.MinPrice,
		&i.CurrentPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SoldAt,
		&i.SoldTo,
	)
	return i, err
}

const getProductImages = `-- name: GetProductImages :one
SELECT images FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductImages(ctx context.Context, id uuid.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getProductImages, id)
	var images []string
	err := row.Scan(&images)
	return images, err
}

const getProductsBySellerID = `-- name: GetProductsBySellerID :many
SELECT id, title, description, seller_id, images, min_price, current_price, created_at, updated_at, sold_at, sold_to FROM products
WHERE seller_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetProductsBySellerIDParams struct {
	SellerID uuid.UUID `json:"seller_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) GetProductsBySellerID(ctx context.Context, arg GetProductsBySellerIDParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsBySellerID, arg.SellerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.SellerID,
			&i.Images,
			&i.MinPrice,
			&i.CurrentPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SoldAt,
			&i.SoldTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProductAsSold = `-- name: MarkProductAsSold :one
UPDATE products
SET sold_at = NOW(), sold_to = $2, current_price = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, seller_id, images, min_price, current_price, created_at, updated_at, sold_at, sold_to
`

type MarkProductAsSoldParams struct {
	ID           uuid.UUID  `json:"id"`
	SoldTo       *uuid.UUID `json:"sold_to"`
	CurrentPrice int32      `json:"current_price"`
}

func (q *Queries) MarkProductAsSold(ctx context.Context, arg MarkProductAsSoldParams) (Product, error) {
	row := q.db.QueryRow(ctx, markProductAsSold, arg.ID, arg.SoldTo, arg.CurrentPrice)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SellerID,
		&i.Images,
		&i.MinPrice,
		&i.CurrentPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SoldAt,
		&i.SoldTo,
	)
	return i, err
}

const updateProductCurrentPrice = `-- name: UpdateProductCurrentPrice :exec
UPDATE products
SET current_price = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateProductCurrentPriceParams struct {
	ID           uuid.UUID `json:"id"`
	CurrentPrice int32     `json:"current_price"`
}

func (q *Queries) UpdateProductCurrentPrice(ctx context.Context, arg UpdateProductCurrentPriceParams) error {
	_, err := q.db.Exec(ctx, updateProductCurrentPrice, arg.ID, arg.CurrentPrice)
	return err
}

const updateProductImages = `-- name: UpdateProductImages :one
UPDATE products
SET images = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, seller_id, images, min_price, current_price, created_at, updated_at, sold_at, sold_to
`

type UpdateProductImagesParams struct {
	ID     uuid.UUID `json:"id"`
	Images []string  `json:"images"`
}

func (q *Queries) UpdateProductImages(ctx context.Context, arg UpdateProductImagesParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductImages, arg.ID, arg.Images)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.SellerID,
		&i.Images,
		&i.MinPrice,
		&i.CurrentPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SoldAt,
		&i.SoldTo,
	)
	return i, err
}
